#!/bin/sh
# Regenerates nginx/includes/cloudflare-realip.inc from Cloudflare's published
# ranges.
#
# Behind Cloudflare every request reaches nginx from a Cloudflare address, so
# $remote_addr — which is what access logs, rate limits and fail2ban all read —
# would be Cloudflare's rather than the visitor's. These directives tell nginx
# to trust the CF-Connecting-IP header, but *only* when the connection itself
# comes from one of these ranges; a forged header from anywhere else is ignored.
#
# Cloudflare changes the list rarely. Re-run this after they announce a change,
# then `docker compose -f docker-compose.prod.yml exec nginx nginx -s reload`.
set -e

OUT="$(dirname "$0")/../nginx/includes/cloudflare-realip.inc"

{
  echo "# Generated by scripts/update-cloudflare-ips.sh on $(date -u +%Y-%m-%d)."
  echo "# Do not edit by hand — re-run the script instead."
  echo
  curl -fsS https://www.cloudflare.com/ips-v4 | sed 's/^/set_real_ip_from /; s/$/;/'
  curl -fsS https://www.cloudflare.com/ips-v6 | sed 's/^/set_real_ip_from /; s/$/;/'
  echo
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
} > "$OUT"

echo "Wrote $OUT ($(grep -c set_real_ip_from "$OUT") ranges)"
