"""initial schema

Revision ID: 23240f2aa343
Revises: 
Create Date: 2026-08-27 20:47:37.345052
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '23240f2aa343'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(), nullable=False),
    sa.Column('title_tj', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('title_tr', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_certificates_id'), 'about_certificates', ['id'], unique=False)
    op.create_table('about_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_title_ru', sa.String(), nullable=False),
    sa.Column('hero_title_tj', sa.String(), nullable=False),
    sa.Column('hero_title_en', sa.String(), nullable=False),
    sa.Column('hero_title_tr', sa.String(), nullable=False),
    sa.Column('hero_description_ru', sa.String(), nullable=False),
    sa.Column('hero_description_tj', sa.String(), nullable=False),
    sa.Column('hero_description_en', sa.String(), nullable=False),
    sa.Column('hero_description_tr', sa.String(), nullable=False),
    sa.Column('story_title_ru', sa.String(), nullable=False),
    sa.Column('story_title_tj', sa.String(), nullable=False),
    sa.Column('story_title_en', sa.String(), nullable=False),
    sa.Column('story_title_tr', sa.String(), nullable=False),
    sa.Column('story_paragraphs_ru', sa.Text(), nullable=False),
    sa.Column('story_paragraphs_tj', sa.Text(), nullable=False),
    sa.Column('story_paragraphs_en', sa.Text(), nullable=False),
    sa.Column('story_paragraphs_tr', sa.Text(), nullable=False),
    sa.Column('timeline_title_ru', sa.String(), nullable=False),
    sa.Column('timeline_title_tj', sa.String(), nullable=False),
    sa.Column('timeline_title_en', sa.String(), nullable=False),
    sa.Column('timeline_title_tr', sa.String(), nullable=False),
    sa.Column('timeline_description_ru', sa.String(), nullable=False),
    sa.Column('timeline_description_tj', sa.String(), nullable=False),
    sa.Column('timeline_description_en', sa.String(), nullable=False),
    sa.Column('timeline_description_tr', sa.String(), nullable=False),
    sa.Column('certificates_title_ru', sa.String(), nullable=False),
    sa.Column('certificates_title_tj', sa.String(), nullable=False),
    sa.Column('certificates_title_en', sa.String(), nullable=False),
    sa.Column('certificates_title_tr', sa.String(), nullable=False),
    sa.Column('certificates_description_ru', sa.String(), nullable=False),
    sa.Column('certificates_description_tj', sa.String(), nullable=False),
    sa.Column('certificates_description_en', sa.String(), nullable=False),
    sa.Column('certificates_description_tr', sa.String(), nullable=False),
    sa.Column('clients_title_ru', sa.String(), nullable=False),
    sa.Column('clients_title_tj', sa.String(), nullable=False),
    sa.Column('clients_title_en', sa.String(), nullable=False),
    sa.Column('clients_title_tr', sa.String(), nullable=False),
    sa.Column('clients_quote_ru', sa.String(), nullable=False),
    sa.Column('clients_quote_tj', sa.String(), nullable=False),
    sa.Column('clients_quote_en', sa.String(), nullable=False),
    sa.Column('clients_quote_tr', sa.String(), nullable=False),
    sa.Column('stat_years_value', sa.Integer(), nullable=False),
    sa.Column('stat_years_suffix', sa.String(), nullable=False),
    sa.Column('stat_projects_value', sa.Integer(), nullable=False),
    sa.Column('stat_projects_suffix', sa.String(), nullable=False),
    sa.Column('stat_employees_value', sa.Integer(), nullable=False),
    sa.Column('stat_employees_suffix', sa.String(), nullable=False),
    sa.Column('stat_tonnage_value', sa.Integer(), nullable=False),
    sa.Column('stat_tonnage_suffix', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_content_id'), 'about_content', ['id'], unique=False)
    op.create_table('about_timeline_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year_ru', sa.String(), nullable=False),
    sa.Column('year_tj', sa.String(), nullable=False),
    sa.Column('year_en', sa.String(), nullable=False),
    sa.Column('year_tr', sa.String(), nullable=False),
    sa.Column('title_ru', sa.String(), nullable=False),
    sa.Column('title_tj', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('title_tr', sa.String(), nullable=False),
    sa.Column('description_ru', sa.String(), nullable=False),
    sa.Column('description_tj', sa.String(), nullable=False),
    sa.Column('description_en', sa.String(), nullable=False),
    sa.Column('description_tr', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_timeline_items_id'), 'about_timeline_items', ['id'], unique=False)
    op.create_table('contact_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_ru', sa.String(), nullable=False),
    sa.Column('address_tj', sa.String(), nullable=False),
    sa.Column('address_en', sa.String(), nullable=False),
    sa.Column('address_tr', sa.String(), nullable=False),
    sa.Column('map_url', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('whatsapp', sa.String(), nullable=False),
    sa.Column('social_instagram_url', sa.String(), nullable=False),
    sa.Column('social_instagram_enabled', sa.Boolean(), nullable=False),
    sa.Column('social_telegram_url', sa.String(), nullable=False),
    sa.Column('social_telegram_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_info_id'), 'contact_info', ['id'], unique=False)
    op.create_table('contact_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_ru', sa.String(), nullable=False),
    sa.Column('label_tj', sa.String(), nullable=False),
    sa.Column('label_en', sa.String(), nullable=False),
    sa.Column('label_tr', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_interests_id'), 'contact_interests', ['id'], unique=False)
    op.create_table('hero_slides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_ru', sa.String(), nullable=False),
    sa.Column('title_tj', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('title_tr', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('product_link', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hero_slides_id'), 'hero_slides', ['id'], unique=False)
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('cover_path', sa.String(), nullable=False),
    sa.Column('published_at', sa.Date(), nullable=False),
    sa.Column('title_ru', sa.String(), nullable=False),
    sa.Column('title_tj', sa.String(), nullable=False),
    sa.Column('title_en', sa.String(), nullable=False),
    sa.Column('title_tr', sa.String(), nullable=False),
    sa.Column('excerpt_ru', sa.String(), nullable=True),
    sa.Column('excerpt_tj', sa.String(), nullable=True),
    sa.Column('excerpt_en', sa.String(), nullable=True),
    sa.Column('excerpt_tr', sa.String(), nullable=True),
    sa.Column('body_ru', sa.Text(), nullable=False),
    sa.Column('body_tj', sa.Text(), nullable=False),
    sa.Column('body_en', sa.Text(), nullable=False),
    sa.Column('body_tr', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_articles_id'), 'news_articles', ['id'], unique=False)
    op.create_index(op.f('ix_news_articles_slug'), 'news_articles', ['slug'], unique=True)
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('logo_path', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partners_id'), 'partners', ['id'], unique=False)
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=False),
    sa.Column('name_tj', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_tr', sa.String(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.create_table('showrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_ru', sa.String(), nullable=False),
    sa.Column('city_tj', sa.String(), nullable=False),
    sa.Column('city_en', sa.String(), nullable=False),
    sa.Column('city_tr', sa.String(), nullable=False),
    sa.Column('address_ru', sa.String(), nullable=False),
    sa.Column('address_tj', sa.String(), nullable=False),
    sa.Column('address_en', sa.String(), nullable=False),
    sa.Column('address_tr', sa.String(), nullable=False),
    sa.Column('hours_ru', sa.String(), nullable=False),
    sa.Column('hours_tj', sa.String(), nullable=False),
    sa.Column('hours_en', sa.String(), nullable=False),
    sa.Column('hours_tr', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('route_url', sa.String(), nullable=False),
    sa.Column('photo_path', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_showrooms_id'), 'showrooms', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), server_default='admin', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_showrooms_id'), table_name='showrooms')
    op.drop_table('showrooms')
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_partners_id'), table_name='partners')
    op.drop_table('partners')
    op.drop_index(op.f('ix_news_articles_slug'), table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_id'), table_name='news_articles')
    op.drop_table('news_articles')
    op.drop_index(op.f('ix_hero_slides_id'), table_name='hero_slides')
    op.drop_table('hero_slides')
    op.drop_index(op.f('ix_contact_interests_id'), table_name='contact_interests')
    op.drop_table('contact_interests')
    op.drop_index(op.f('ix_contact_info_id'), table_name='contact_info')
    op.drop_table('contact_info')
    op.drop_index(op.f('ix_about_timeline_items_id'), table_name='about_timeline_items')
    op.drop_table('about_timeline_items')
    op.drop_index(op.f('ix_about_content_id'), table_name='about_content')
    op.drop_table('about_content')
    op.drop_index(op.f('ix_about_certificates_id'), table_name='about_certificates')
    op.drop_table('about_certificates')
    # ### end Alembic commands ###
