"""about content home section

Revision ID: 8d17d010265d
Revises: e54b2971ca5a
Create Date: 2026-08-29 02:41:33.979352

Adds `home_title_*`/`home_description_*` to `about_content` for the
homepage's "О компании" teaser (`AboutStatsSection`), previously hardcoded
in `messages/*.json` under `home.about.title`/`.body`. Backfills the
existing singleton row with that same copy via `server_default` (same
approach as `e54b2971ca5a`'s downgrade), then drops the default — new rows
always come from `seed_about_content`/an explicit admin edit, never an
implicit default.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8d17d010265d'
down_revision: Union[str, None] = 'e54b2971ca5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_HOME_TITLE = "Производим профильные системы в Душанбе с 2006 года"
_HOME_DESCRIPTION = (
    "Полный цикл: экструзия, сборка конструкций, замер, монтаж и сервис. С 2025 года — и "
    "алюминий."
)


def upgrade() -> None:
    for locale in ("ru", "tj", "en", "tr"):
        op.add_column(
            'about_content',
            sa.Column(f'home_title_{locale}', sa.String(), nullable=False, server_default=_HOME_TITLE),
        )
        op.add_column(
            'about_content',
            sa.Column(
                f'home_description_{locale}', sa.String(), nullable=False, server_default=_HOME_DESCRIPTION
            ),
        )
        op.alter_column('about_content', f'home_title_{locale}', server_default=None)
        op.alter_column('about_content', f'home_description_{locale}', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('about_content', 'home_description_tr')
    op.drop_column('about_content', 'home_description_en')
    op.drop_column('about_content', 'home_description_tj')
    op.drop_column('about_content', 'home_description_ru')
    op.drop_column('about_content', 'home_title_tr')
    op.drop_column('about_content', 'home_title_en')
    op.drop_column('about_content', 'home_title_tj')
    op.drop_column('about_content', 'home_title_ru')
    # ### end Alembic commands ###
