"""products and product sections

Revision ID: b41f7c92d3ae
Revises: 23240f2aa343
Create Date: 2026-08-28 12:10:00.000000

The product page moves off the frontend's static `data/products.ts` and into
the database: a product (photo, title, description — what a card shows and what
the page's opening screen is built from), the categories it is listed in, and
an ordered list of content sections whose order *is* the page layout.

Written by hand rather than autogenerated — `content` is JSONB and the link
table has no model class of its own, both of which autogenerate renders less
clearly than this.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'b41f7c92d3ae'
down_revision: Union[str, None] = '23240f2aa343'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'products',
        sa.Column('id', sa.Integer(), nullable=False),
        # Nullable: ЭКОЛАЙН has no render at all (the client never sent that
        # folder), and the seed has to be able to say so.
        sa.Column('image_path', sa.String(), nullable=True),
        sa.Column('title_ru', sa.String(), nullable=False),
        sa.Column('title_tj', sa.String(), nullable=False),
        sa.Column('title_en', sa.String(), nullable=False),
        sa.Column('title_tr', sa.String(), nullable=False),
        sa.Column('description_ru', sa.Text(), nullable=False),
        sa.Column('description_tj', sa.Text(), nullable=False),
        sa.Column('description_en', sa.Text(), nullable=False),
        sa.Column('description_tr', sa.Text(), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)

    op.create_table(
        'product_category_links',
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('product_id', 'category_id'),
    )

    op.create_table(
        'product_sections',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product_id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_product_sections_id'), 'product_sections', ['id'], unique=False)
    op.create_index(
        op.f('ix_product_sections_product_id'), 'product_sections', ['product_id'], unique=False
    )


def downgrade() -> None:
    op.drop_index(op.f('ix_product_sections_product_id'), table_name='product_sections')
    op.drop_index(op.f('ix_product_sections_id'), table_name='product_sections')
    op.drop_table('product_sections')
    op.drop_table('product_category_links')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
